# Generated by Django 4.1.5 on 2023-01-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.SmallIntegerField(default=0),
        ),
    ]
